<?php
namespace ThanhVo\Worldpay\WPG;

use mysql_xdevapi\Exception;

class Exponent
{
    /**
     * @var string[]
     */
    protected $exponent = [
        'AFN' => 2,
        'DZD' => 2,
        'AOA' => 2,
        'AON' => 2,
        'ANG' => 2,
        'AWG' => 2,
        'AUD' => 2,
        'ATS' => 2,
        'AZN' => 2,
        'BSD' => 2,
        'BHD' => 3,
        'BDT' => 2,
        'BBD' => 2,
        'BYN' => 2,
        'BEF' => 0,
        'BZD' => 2,
        'BMD' => 2,
        'BTN' => 2,
        'BOB' => 2,
        'BAM' => 2,
        'BWP' => 2,
        'BRL' => 2,
        'BND' => 2,
        'BGL' => 2,
        'BIF' => 2,
        'KHR' => 2,
        'CAD' => 2,
        'CVE' => 2,
        'KYD' => 2,
        'XOF' => 0,
        'XAF' => 0,
        'XPF' => 0,
        'CLP' => 2,
        'COP' => 2,
        'KMF' => 0,
        'CDF' => 2,
        'CRC' => 2,
        'HRK' => 2,
        'CYP' => 2,
        'CZK' => 2,
        'DKK' => 2,
        'DEM' => 2,
        'DJF' => 2,
        'STD' => 2,
        'DOP' => 2,
        'NLG' => 2,
        'XCD' => 2,
        'ECS' => 2,
        'EGP' => 2,
        'SVC' => 2,
        'ERN' => 2,
        'EEK' => 2,
        'ETB' => 2,
        'EUR' => 2,
        'FKP' => 2,
        'FJD' => 2,
        'FIM' => 2,
        'FRF' => 2,
        'GMD' => 2,
        'GEL' => 2,
        'GHS' => 2,
        'GIP' => 2,
        'GRD' => 0,
        'GTQ' => 2,
        'GNF' => 0,
        'GYD' => 2,
        'HTG' => 2,
        'HNL' => 2,
        'HKD' => 2,
        'HUF' => 0,
        'ISK' => 2,
        'INR' => 2,
        'IDR' => 0,
        'IRR' => 2,
        'IQD' => 3,
        'IEP' => 2,
        'ITL' => 0,
        'JMD' => 2,
        'JPY' => 0,
        'JOD' => 3,
        'KZT' => 2,
        'KES' => 2,
        'KWD' => 3,
        'LAK' => 2,
        'LVL' => 2,
        'LBP' => 2,
        'LSL' => 2,
        'LRD' => 2,
        'LYD' => 3,
        'LTL' => 2,
        'LUF' => 0,
        'MOP' => 2,
        'MKD' => 2,
        'MGA' => 0,
        'MGF' => 0,
        'MWK' => 2,
        'MYR' => 2,
        'MVR' => 2,
        'MTL' => 2,
        'MRO' => 2,
        'MUR' => 2,
        'MXN' => 2,
        'MDL' => 2,
        'MNT' => 2,
        'MAD' => 2,
        'MZN' => 2,
        'MMK' => 2,
        'NAD' => 2,
        'NPR' => 2,
        'BGN' => 2,
        'ILS' => 2,
        'PLN' => 2,
        'RON' => 2,
        'RSD' => 2,
        'TWD' => 2,
        'TRY' => 2,
        'NZD' => 2,
        'NIO' => 2,
        'NGN' => 2,
        'KPW' => 2,
        'NOK' => 2,
        'ARS' => 2,
        'PKR' => 2,
        'PAB' => 2,
        'PGK' => 2,
        'PYG' => 0,
        'PEN' => 2,
        'UYU' => 2,
        'PHP' => 2,
        'PTE' => 0,
        'GBP' => 2,
        'QAR' => 2,
        'OMR' => 3,
        'ROL' => 2,
        'RUB' => 2,
        'RWF' => 0,
        'WST' => 2,
        'SAR' => 2,
        'CSD' => 2,
        'SCR' => 2,
        'SLL' => 2,
        'SGD' => 2,
        'SKK' => 2,
        'SIT' => 2,
        'SBD' => 2,
        'SOS' => 2,
        'ZAR' => 2,
        'KRW' => 0,
        'ESP' => 0,
        'LKR' => 2,
        'SHP' => 2,
        'SDP' => 2,
        'SRD' => 2,
        'SRG' => 2,
        'SZL' => 2,
        'SEK' => 2,
        'CHF' => 2,
        'SYP' => 2,
        'TJS' => 2,
        'TZS' => 2,
        'THB' => 2,
        'TOP' => 2,
        'TTD' => 2,
        'TND' => 3,
        'TRL' => 0,
        'TMT' => 2,
        'AED' => 2,
        'UGX' => 2,
        'UAH' => 2,
        'USD' => 2,
        'UZS' => 2,
        'VUV' => 2,
        'VEB' => 2,
        'VEF' => 2,
        'VND' => 0,
        'YER' => 2,
        'CNY' => 2,
        'YUM' => 2,
        'ZMW' => 2,
        'ZWD' => 2,
    ];

    /**
     * @param string $currency
     * @return int
     */
    public function getByCurrency(string $currency): int
    {
        if (!isset($this->exponent[$currency])) {
            throw new Exception(printf('Currency don\'t support'));
        }
        return $this->exponent[$currency];
    }
}
